version: "3"
services:
  app:
    build: app
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
      - ./:/var/www/html/source
  phpfpm:
    build: fpm
    links:
      - db
    volumes: *appvolumes
  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: ./env
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata:



